language: python

python:
  - "3.6"

before_install:
  - pip install pytest-cov python-coveralls sphinx_rtd_theme

install:
  - python setup.py install

script:
  - pytest --cov=texpy

after_success:
  - coveralls
  - sphinx-apidoc -fo docs/source/api pyxem
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ${TRAVIS_BUILD_DIR}/docs/build
  on:
    branch: master