language: python

python:
  - "3.6"

before_install:
  - pip install pytest-cov python-coveralls sphinx sphinx_rtd_theme autodocsumm

install:
  - python setup.py install

script:
  - pytest --cov=texpy

after_success:
  - coveralls
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/build
  on:
    branch: master