language: python

env:
  global:
    - DEPS="ipython tqdm"
    - TEST_DEPS="pytest>=5.0 pytest-cov>=2.8.1 coveralls>=1.10 coverage>=5.0"

matrix:
  include:
  - env: export PYTHON=3.7
  - env: export PYTHON=3.6
  - env: export PYTHON=3.7
    os: osx
    language: generic

sudo: True #for Miniconda

before_install:
  # Install miniconda
  - if [ $TRAVIS_OS_NAME = osx ]; then
      curl "https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh" -o miniconda.sh;
    else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh;
    ./miniconda.sh -b -p $HOME/miniconda;
    hash -r;
  # setup environment
  - source $HOME/miniconda/bin/activate root;
    conda update -y conda;
    conda config --append channels conda-forge;
    conda create -n testenv --yes python=$PYTHON;
    conda activate testenv;
  - conda info -a
  - df -h

install:
  - conda install -y $DEPS $TEST_DEPS;
  - pip install .

script:
  - export MPLBACKEND=Agg
  - pytest --cov=orix

after_success:
  - coveralls
