name: doc-dependencies-for-binder
channels:
  - conda-forge
dependencies:
  - dask
  - diffpy.structure>=3
  - h5py
  - matplotlib>=3.3
  - matplotlib-scalebar
  - numba
  - numpy
  - numpy-quaternion
  - pooch>=0.13
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm