name: build

on: [push, pull_request]

jobs:
  build-with-pip:
    name: ${{ matrix.os }}/py${{ matrix.python-version }}/pip
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      MPLBACKEND: agg
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9]
        include:
          # Oldest supported version of main dependencies on Python 3.6
          - os: ubuntu-latest
            python-version: 3.6
            OLDEST_SUPPORTED_VERSION: true
            DEPENDENCIES: diffpy.structure==3  matplotlib==3.3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display versions
        run: python -V; pip -V
      - name: Install depedencies and package
        shell: bash
        run: pip install -U -e .'[doc, tests]'
      - name: Install oldest supported version
        if: ${{ matrix.OLDEST_SUPPORTED_VERSION }}
        run: pip install ${{ matrix.DEPENDENCIES }}
      - name: Run tests
        run: pytest --cov=orix --pyargs orix
      - name: Generate line coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: coverage report --show-missing
      - name: Upload coverage to Coveralls
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  coveralls-finish:
    needs: build-with-pip
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
